config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/resource-catalogue-ui-eosc:
      branch: master
      repo: https://github.com/madgeek-arc/resource-catalogue-ui-eosc
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-mustard-tarantula.sh
        container: qc.acc_snazzy-heliotrope-barracuda
  QC.Doc:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-russet-sloth.sh
        container: qc.doc_nippy-russet-ragdoll
      github.com/madgeek-arc/resource-catalogue-ui-eosc git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-ruby-hummingbird.sh
        container: qc.doc_homely-lavender-akita
      github.com/madgeek-arc/resource-catalogue-ui-eosc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-indigo-frise.sh
        container: qc.doc_bumpy-viridian-duck
  QC.Lic:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-sepia-cheetah.sh
        container: qc.lic_geeky-silver-capuchin
  QC.Sty:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-lime-antelope.sh
        container: qc.sty_scanty-cinnabar-gar
      github.com/madgeek-arc/resource-catalogue-ui-eosc jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-celadon-rattlesnake.sh
        container: qc.sty_goopy-orchid-cattle
  QC.Ver:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-mustard-birman.sh
        container: qc.ver_zippy-peach-moth
timeout: 5400
